Add field to include and remove gif
WindSekirun/NaraeImagePicker pull request #19
Opened 2019-10-12 06:11 UTC by deepakkumardk

Added a filed as includeGif to handle this issue and minor code cleanup

2019-10-12 10:55 UTC, WindSekirun requested changes
There are some minor improvements, but looks good to me!

2019-10-12 10:55 UTC, WindSekirun commented on library/src/main/java/com/github/windsekirun/naraeimagepicker/module/PickerSet.kt
> +                .sortedBy { it.name.toLowerCase(Locale.ENGLISH) }
Do you have reason to using 'Locale.ENGLISH'? if not, Use 'Locale.getDefault()' will support other conturies.

2019-10-12 10:55 UTC, WindSekirun commented on library/src/main/java/com/github/windsekirun/naraeimagepicker/module/PickerSet.kt
> +                            list.add(FileItem(id, image))
I think I can make it simpler.

```
if (file.exists() && (item.includeGIf || file.extension != "gif")) list.add(FileItem(id, image))
```

2019-10-12 14:11 UTC, deepakkumardk commented
Committed the requested changes.

2019-10-13 14:37 UTC, WindSekirun approved these changes

2019-10-13 14:38 UTC, merged